export { default as bubble } from './bubble'
export { default as smallCaps } from './small_caps'
export { default as superscript } from './superscript'
export { default as upsideDown } from './upside_down'
export { default as wide } from './wide'
